name: Тестирование bash скрипта
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Создание файла ввода
        run: |
          echo "Привет мир!" > /tmp/input.txt
          echo "Это тестовый файл." >> /tmp/input.txt
          echo "Слово \"тест\" встречается дважды." >> /tmp/input.txt

      - name: Запуск скрипта с параметрами all symbols
        run: |
          echo "тест" | ./script.sh /tmp/input.txt /tmp/output.txt
          echo "all symbols" | ./script.sh /tmp/input.txt /tmp/output.txt

      - name: Запуск скрипта с параметрами num of lines
        run: |
          echo "тест" | ./script.sh /tmp/input.txt /tmp/output.txt
          echo "num of lines" | ./script.sh /tmp/input.txt /tmp/output.txt
