name: Тестирование bash скрипта
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Создание файла ввода
        run: |
          chmod +x script.sh
          ./script.sh test_input test_output
          if [[ $? == 0 ]] then
            echo "Program finished with code 0"
          else
            echo "Program finished with code"
